--- #TO BRING UP AN EC2 INSTANCE
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
  - credentials.yml
  tasks:
  - name: create ec2 key pair
    ec2_key:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      name: sagar
      key_material: "{{ item }}"
      state: present
    with_file: id_rsa.pub
  - name: Bring an instance up
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      #Latest ubuntu AMI
      image: ami-40d28157
      instance_type: t2.micro
      vpc_subnet_id: "{{ subnet_group }}"
      assign_public_ip: yes
      group_id: "{{ security-group }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 20
          delete_on_termination: true
      instance_tags:
        Name: mariana-test
      key_name: sagar
      wait: yes
    register: ec2
  
  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=launched
    with_items: '{{ ec2.instances }}'
  
  - name: Wait for SSH to come up
    wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ ec2.instances }}'

- name: Configure instance
  hosts: launched
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
  - name: install python-2
    raw: apt-get -y install python-simplejson
  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: clone git URL
    git:
      repo: "https://github.com/octocat/Hello-World"
      dest: /var/www/
      version: master
